version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "portal-parceiro-back"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16s0xrgyf24d2"
s3_prefix = "portal-parceiro-back"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
