AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for portal-parceiro-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.8
    MemorySize: 1024
    Timeout: 120
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Authorization,Content-Type,If-Match'"
      AllowOrigin: "'*'"

Resources:

  OrgsScanFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "PP-OrgsScanFn-${Ambiente}"
      Description: Retorna um contrato.
      CodeUri: Apis/Organizations/Scan
      Handler: app.lambda_handler
      Tracing: Active
      Events:
<<<<<<< HEAD
        OrgsScan:
=======
        OrgsApi:
>>>>>>> staging
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /orgs
            Method: get


  OrgsGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "PP-OrgsGetFn-${Ambiente}"
      Description: Retorna um contrato.
      CodeUri: Apis/Organizations/Get
      Handler: app.lambda_handler
      Tracing: Active
      Events:
<<<<<<< HEAD
        OrgsGet:
=======
        OrgsApi:
>>>>>>> staging
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /orgs/{id}
            Method: get

  OrgsCreateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "PP-OrgsCreateFn-${Ambiente}"
      Description: Retorna um contrato.
      CodeUri: Apis/Organizations/Create
      Handler: app.lambda_handler
      Tracing: Active
      Events:
<<<<<<< HEAD
        OrgsCreate:
=======
        OrgsApi:
>>>>>>> staging
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /orgs
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OrgsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orgs/"
  OrgsScanFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt OrgsScanFunction.Arn
  OrgsScanFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt OrgsScanFunctionRole.Arn
  OrgsCreateFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt OrgsCreateFunction.Arn
    OrgsCreateFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt OrgsCreateFunctionRole.Arn
  OrgsGetFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt OrgsGetFunction.Arn
    OrgsGetFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt OrgsGetFunctionRole.Arn
